-- AlterTable
ALTER TABLE "Business" ALTER COLUMN "services" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "keywords" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "phones" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "targetLocations" SET DEFAULT ARRAY[]::TEXT[];
